### ISSUE TITLE
Action can't parse `INPUT_MIN_LINES` when it's not provided

### ISSUE THREAD

**Issue by h1alexbel** [tracehubpm/code-review-action#51]
```text
Exception in thread "main" java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at git.tracehub.codereview.action.Entry.main(Entry.java:92)
```

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#53](https://github.com/tracehubpm/code-review-action/issues/53), [#54](https://github.com/tracehubpm/code-review-action/issues/54) are still not solved.

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.14`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.15`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.16`
